# Generated by Django 2.1 on 2022-05-25 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 2, 45, 0, 251742, tzinfo=utc)),
        ),
    ]
